# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import verify.models


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=verify.models.get_image_path),
        ),
    ]
