# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verify', '0002_auto_20160629_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verify',
            old_name='First_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='verify',
            name='Second_name',
        ),
    ]
