# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-30 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.DecimalField(decimal_places=0, max_digits=8)),
                ('appointment', models.DateTimeField()),
                ('allergies', models.CharField(max_length=180)),
                ('pastMedication', models.CharField(max_length=180)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=2)),
                ('sign', models.CharField(max_length=120)),
            ],
        ),
    ]
